/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as ApiSplatRouteImport } from './routes/api.$';
import { Route as AuthDeviceRouteImport } from './routes/auth.device';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthDeviceRoute = AuthDeviceRouteImport.update({
  id: '/auth/device',
  path: '/auth/device',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/api/$': typeof ApiSplatRoute;
  '/auth/device': typeof AuthDeviceRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/api/$': typeof ApiSplatRoute;
  '/auth/device': typeof AuthDeviceRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/api/$': typeof ApiSplatRoute;
  '/auth/device': typeof AuthDeviceRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/api/$' | '/auth/device';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/api/$' | '/auth/device';
  id: '__root__' | '/' | '/api/$' | '/auth/device';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ApiSplatRoute: typeof ApiSplatRoute;
  AuthDeviceRoute: typeof AuthDeviceRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/$': {
      id: '/api/$';
      path: '/api/$';
      fullPath: '/api/$';
      preLoaderRoute: typeof ApiSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/auth/device': {
      id: '/auth/device';
      path: '/auth/device';
      fullPath: '/auth/device';
      preLoaderRoute: typeof AuthDeviceRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSplatRoute: ApiSplatRoute,
  AuthDeviceRoute: AuthDeviceRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { createStart } from '@tanstack/react-start';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
